#!/bin/sh

if [ ! -d /usr/local/Homebrew/.git ]; then
	ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

packages=(
	zsh
	git
	pandoc
	go
)

# Update homebrew before installing any packages
brew update

for package in ${packages[@]}; do
		if brew list -1 | grep -q "^${package}\$"; then
			# Upgrade already installed package
			brew upgrade ${package}
		else
			# Install new package not on the system
			brew install ${package}
		fi
done

if [ -x "/Applications/Sublime Text 2.app/Contents/SharedSupport/bin/subl" ]; then
	ln -f -s "/Applications/Sublime Text 2.app/Contents/SharedSupport/bin/subl" /usr/local/bin/subl2
else
	echo "Sublime Text 2 is not installed..."
fi

if [ -x "/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl" ]; then
	ln -f -s "/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl" /usr/local/bin/subl
else
	echo "Sublime Text 3 is not installed..."
fi

# go
mkdir -p $(echo $GOPATH | tr ":" " ")
mkdir -p $(echo $GOBIN | tr ":" " ")

mkdir -p ~/.go/src/github.com

if [ ! -L ~/.go/src/github.com/mojang ]; then
	ln -s ~/Projects/mojang ~/.go/src/github.com/mojang
fi

if [ ! -L ~/.go/src/github.com/zeeraw ]; then
	ln -s ~/Projects/zeeraw ~/.go/src/github.com/zeeraw
fi

if [ ! -L ~/.go/src/github.com/pkmngo-odi ]; then
	ln -s ~/Projects/pkmngo-odi ~/.go/src/github.com/pkmngo-odi
fi
