#!/bin/sh

DOTFILES=${PWD}
LINKS="$DOTFILES/links"

if [ ! -d $HOME/.zprezto ]; then
  git clone --recursive https://github.com/sorin-ionescu/prezto.git "$HOME/.zprezto"
else
  cd $HOME/.zprezto && \
    git pull --recurse-submodules && \
    cd $DOTFILES
fi

echo "Setting up symlinks:"

while read line; do
  if [[ ! $line == \#* ]] && [ -n "$line" ]; then
    IFS=","
    set -- $line

    # dest - the file to override in ~/
    # src - the source file in the dotfiles repo
    dest=$(echo $1 | sed 's/^ *//g' | sed 's/ *$//g')
    dest=${dest/"~"/$HOME}
    src=$(echo $2 | sed 's/^ *//g' | sed 's/ *$//g')
    src=$DOTFILES$src

    # unlink
    if [ -L $dest ]; then
      unlink $dest
    fi

    # delete file
    if [ -a $dest ]; then
      rm -rf $dest
    fi

    # create dir
    mkdir -p -- "$(dirname -- "$dest")"

    # create link
    ln -sfF $src $dest
    echo "$src -> $dest"
  fi
done < $LINKS