#!/bin/sh

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
DOTFILES=${DIR}
LINKS="$DOTFILES/links"

if [ ! -d $HOME/.zprezto ]; then
	echo "[√] installing prezto"
	git clone --recursive https://github.com/sorin-ionescu/prezto.git "$HOME/.zprezto"
else
	echo "[√] updating prezto"
	cd $HOME/.zprezto && \
		git pull --recurse-submodules && \
		cd $DOTFILES
fi

echo "[√] creating directories"

mkdir -p "$HOME/.bin/"

echo "[√] creating files"

touch "$HOME/.secret"

echo "[√] setting up symlinks"

while read line; do
	if [[ ! $line == \#* ]] && [ -n "$line" ]; then
		IFS=","
		set -- $line

		# dest - the file to override in ~/
		# src - the source file in the dotfiles repo
		dest=$(echo $1 | sed 's/^ *//g' | sed 's/ *$//g')
		dest=${dest/"~"/$HOME}
		src=$(echo $2 | sed 's/^ *//g' | sed 's/ *$//g')
		src=$DOTFILES$src

		# unlink
		if [ -L $dest ]; then
			unlink $dest
		fi

		# delete file
		if [ -a $dest ]; then
			rm -rf $dest
		fi

		# create dir
		mkdir -p -- "$(dirname -- "$dest")"

		# create link
		ln -sfF $src $dest
		echo "$src -> $dest"
	fi
done < $LINKS
